version: "3.8"

services:
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - crawler
    networks:
      - crawler_network

  crawler:
    build:
      context: .
    ports:
      - "50000:50000"
      - "8090:8090"
    volumes:
      - /app/:/app/
    networks:
      - crawler_network

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: "vGXCa1m)vCC+"
    volumes:
      - redis_data:/data
    networks:
      - crawler_network

networks:
  crawler_network:
volumes:
  redis_data: